# src/commands/github-write.yaml
# yamllint disable rule:line-length
---
description: |
  Support for Argo or Flux GitOps orchestration. Individual application pipelines can
  perform direct writes of deployment configuration files to common git repositories.

parameters:

  file-source:
    description: Source path for file(s) to be written.
    type: string

  file-destination: 
    description: Target path for file(s) to be written.
    type: string

  repository-url:
    description: GitHub repository URL where file(s) will be written.
    type: string

  branch:
    description: GitHub repository branch where file(s) will be written. Default is main.
    type: string
    default: "main"

  commit-message:
    description: Commit message for file(s) to be written.
    type: string

steps: