# src/commands/op-kubeconfig.yml
# yamllint disable rule:line-length
---

description: Set ~/.kube/config from from base64 encrypted file contents pulled from 1password

parameters:

  op-value:
    description: 1password vault item containing kubeconfig in base64
    type: string

steps:
  - run:
      name: write temporary template file
      command: echo "op://<< parameters.op-value >>" > kubeconfig.tpl
  - run:
      name: op inject template to local file
      command: op inject -i kubeconfig.tpl -o kubeconfig
  - run:
      name: set ~/.kube/config
      command: |
        mkdir -p ~/.kube
        cat kubeconfig | base64 -d > ~/.kube/config
        chmod o-r ~/.kube/config
        chmod g-r ~/.kube/config
