---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-aws
  namespace: psk-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: psk-aws-control-plane-configuration

  source:
    - repoURL: https://github.com/twplatformlabs/psk-platform-ext-crossplane/chart
      chart: crossplane-aws
      targetRevision: HEAD
      helm:
        valueFiles:
          - $config/roles/sandbox/crossplane-aws/aws-default-values.yaml
    - repoURL: https://github.com/twplatformlabs/psk-aws-control-plane-configuration
      targetRevision: HEAD
      ref: config
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
