# roles/production/external-secrets-operator/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: psk-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: psk-aws-control-plane-configuration

  sources:
    - repoURL: https://charts.external-secrets.io/
      chart: external-secrets
      targetRevision: 2.2.0
      helm:
        valueFiles:
          - $config/roles/sandbox/external-secrets-operator/default-values.yaml
          - $config/roles/sandbox/external-secrets-operator/sandbox-values.yaml
    - repoURL: https://github.com/twplatformlabs/psk-aws-control-plane-configuration
      targetRevision: HEAD
      ref: config
  destination:
    server: https://kubernetes.default.svc
    namespace: psk-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
