---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod-release
  namespace: psk-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: psk-aws-control-plane-configuration

  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istiod
      targetRevision: 1.29.3
      helm:
        parameters:
          - name: revision
            value: 1-29-3
        valueFiles:
          - $config/roles/sandbox/istiod-release/istiod-default-values.yaml
          - $config/roles/sandbox/istiod-release/istiod-sandbox-values.yaml
    - repoURL: https://github.com/twplatformlabs/psk-aws-control-plane-configuration
      targetRevision: HEAD
      ref: config
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istio-validator-1-29-3-istio-system
      managedFieldsManagers:
        - pilot-discovery
